ADD_SUBDIRECTORY ( test_runner )
ADD_SUBDIRECTORY ( profile     )

ADD_SUBDIRECTORY ( libxml  )
ADD_SUBDIRECTORY ( libjson )
ADD_SUBDIRECTORY ( libini  )

ADD_SUBDIRECTORY ( libxml2  )
ADD_SUBDIRECTORY ( libjson2 )

GET_ALL_TARGETS ( LIBRARY_TARGETS )

FOREACH ( TARGET IN LISTS LIBRARY_TARGETS )
    IF ( ${TARGET} MATCHES ".*Unittest.*" )
        SET_TARGET_PROPERTIES ( ${TARGET} PROPERTIES FOLDER "library/test" )
    ELSE ( )
        SET_TARGET_PROPERTIES ( ${TARGET} PROPERTIES FOLDER "library" )
    ENDIF ( )
endforeach ( )
