include_guard(GLOBAL)
message(STATUS "Load module: ${CMAKE_CURRENT_LIST_FILE}")

set(PROJECT_COMPILER ${CMAKE_CXX_COMPILER_ID})
if (WIN32)
    message(FATAL_ERROR "Win32 currently unsupported")
else ()
    if (${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
        set(PROJECT_COMPILER_CLANG ON)
    elseif (${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
        set(PROJECT_COMPILER_GCC ON)
    else ()
        message(WARNING "Unsupported compiler: ${PROJECT_COMPILER}")
    endif ()
endif ()