MESSAGE ( STATUS "Build Info:"                                                          )
MESSAGE ( STATUS "  Type: ${CMAKE_BUILD_TYPE}"                                          )
MESSAGE ( STATUS "  Host System: ${CMAKE_HOST_SYSTEM}"                                  )
MESSAGE ( STATUS "  Host System Name: ${CMAKE_HOST_SYSTEM_NAME}"                        )
MESSAGE ( STATUS "  Host System Processor: ${CMAKE_HOST_SYSTEM_PROCESSOR}"              )
MESSAGE ( STATUS "  Host System Version: ${CMAKE_HOST_SYSTEM_VERSION}"                  )

MESSAGE ( STATUS)
MESSAGE ( STATUS "  Compiler                    : ${CMAKE_CXX_COMPILER}"                )
MESSAGE ( STATUS "  Compiler Version            : ${CMAKE_CXX_COMPILER_VERSION}"        )
MESSAGE ( STATUS "  Linker                      : ${CMAKE_CXX_COMPILER_LINKER}"         )
MESSAGE ( STATUS "  Linker Version              : ${CMAKE_CXX_COMPILER_LINKER_VERSION}" )
MESSAGE ( STATUS "  Compiler Standard           : ${CMAKE_CXX_STANDARD}"                )

MESSAGE ( STATUS )

MESSAGE ( STATUS )
MESSAGE ( STATUS "  Compile options (default)   : ${PROJECT_DEFAULT_COMPILE_OPTIONS}"   )
MESSAGE ( STATUS "  Link    options (default)   : ${PROJECT_DEFAULT_LINK_OPTIONS}"      )
MESSAGE ( STATUS "  Compile options             : ${PROJECT_COMPILE_OPTIONS}"           )
MESSAGE ( STATUS "  Compile definitions         : ${PROJECT_COMPILE_DEFINITIONS}"       )
MESSAGE ( STATUS "  Link options                : ${PROJECT_LINK_OPTIONS}"              )
