include_guard(GLOBAL)
message(STATUS "Load module: ${CMAKE_CURRENT_LIST_FILE}")

# variables to determine
set(PROJECT_SANITIZER_ADDRESS_SUPPORTED OFF)
set(PROJECT_SANITIZER_UNDEFINED_SUPPORTED OFF)
set(PROJECT_SANITIZER_THREAD_SUPPORTED OFF)
set(PROJECT_SANITIZER_LEAK_SUPPORTED OFF)
set(PROJECT_SANITIZER_MEMORY_ENABLED OFF)

if (WIN32)
    # TODO(nikitafin): windows support
    message(FATAL_ERROR "WIN32 currently out of support")
elseif (LINUX)
    set(PROJECT_SANITIZER_ADDRESS_SUPPORTED ON)
    set(PROJECT_SANITIZER_UNDEFINED_SUPPORTED ON)
    set(PROJECT_SANITIZER_THREAD_SUPPORTED ON)

    # TODO(nikitafin): leak, memory
    set(PROJECT_SANITIZER_LEAK_SUPPORTED OFF)
    set(PROJECT_SANITIZER_MEMORY_ENABLED OFF)
else ()
    message(FATAL_ERROR "Unsupported platform (WIN32, LINUX only)")
endif ()

set(PROJECT_SANITIZERS)
set(PROJECT_SANITIZERS_STRING)

set(PROJECT_SANITIZER_ADDRESS OFF)
set(PROJECT_SANITIZER_UNDEFINED OFF)
set(PROJECT_SANITIZER_THREAD OFF)
set(PROJECT_SANITIZER_LEAK OFF)
set(PROJECT_SANITIZER_MEMORY OFF)

if (PROJECT_SANITIZER_ADDRESS_SUPPORTED AND PROJECT_SANITIZER_ADDRESS_ENABLED)
    set(PROJECT_SANITIZER_ADDRESS ON)
    list(APPEND PROJECT_SANITIZERS "address")
endif ()

if (PROJECT_SANITIZER_UNDEFINED_SUPPORTED AND PROJECT_SANITIZER_UNDEFINED_ENABLED)
    set(PROJECT_SANITIZER_UNDEFINED ON)
    list(APPEND PROJECT_SANITIZERS "undefined")
endif ()

if (PROJECT_SANITIZER_THREAD_SUPPORTED AND PROJECT_SANITIZER_THREAD_ENABLED)
    if (PROJECT_SANITIZER_ADDRESS OR PROJECT_SANITIZER_UNDEFINED)
        message(WARNING "Thread sanitizer does not work with Address or Undefined sanitizer enabled. Skip it.")
    else ()
        set(PROJECT_SANITIZER_THREAD ON)
        list(APPEND PROJECT_SANITIZERS "thread")
    endif ()
endif ()

# TODO(nikitafin): leak, memory