name: Basic Pepeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: run pepeline
        run: make all
