name: Basic Pepeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: create base image
        run: docker compose run --remove-orphans builder-ci
      - name: run workflow
        run: docker compose run --remove-orphans builder
