name: Basic Pepeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image and does not push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./util/Dockerfile
          tags: dev
          push: false
      - name: Run pepeline
        run: make
